openapi: 3.2.0
info:
  title: ThreatQ Object Relationship Attributes API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Object Relationship Attributes
paths:
  /{src_object_collection}/{src_object_id}/{dest_object_collection}/{object_link_id}/attributes:
    get:
      tags:
      - Object Relationship Attributes
      summary: List Relationship Attributes for an Object Type
      description: 'This path can be used for any combination of objects installed on the system.


        Examples:


        Attributes for an Indicator / Adversary relationship:

        /adversaries/:adversary_id/indicators/:object_link_id/attributes


        Attributes for an

        Indicator / Indicator relationship: /indicators/:indicator_id/indicators/:object_link_id/attributes'
      parameters:
      - $ref: '#/components/parameters/SrcObject'
      - $ref: '#/components/parameters/SrcObjectId'
      - $ref: '#/components/parameters/DestObject'
      - $ref: '#/components/parameters/ObjectLinkId'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - properties:
                            attribute:
                              $ref: '#/components/schemas/Attribute'
                          type: object
                        - $ref: '#/components/schemas/ObjectLinkAttribute'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getBySrcObjectCollectionBySrcObjectIdByDestObjectCollectionByObjectLinkIdAttributes
      x-operation-id-source: derived
    post:
      tags:
      - Object Relationship Attributes
      summary: Create a Relationship Attribute for an Object Type
      description: 'This path can be used for any combination of objects installed on the system.


        Examples:


        Attributes for an Indicator / Adversary relationship:

        /adversaries/:adversary_id/indicators/:object_link_id/attributes


        Attributes for an

        Indicator / Indicator relationship: /indicators/:indicator_id/indicators/:object_link_id/attributes'
      parameters:
      - $ref: '#/components/parameters/SrcObject'
      - $ref: '#/components/parameters/SrcObjectId'
      - $ref: '#/components/parameters/DestObject'
      - $ref: '#/components/parameters/ObjectLinkId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectLinkAttributeFillable'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectLinkAttribute'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: postBySrcObjectCollectionBySrcObjectIdByDestObjectCollectionByObjectLinkIdAttributes
      x-operation-id-source: derived
  /{src_object_collection}/{src_object_id}/{dest_object_collection}/{object_link_id}/attributes/{object_link_attribute_id}:
    get:
      tags:
      - Object Relationship Attributes
      summary: Get a Single Relationship Attribute for an Object Type
      description: 'This path can be used for any combination of objects installed on the system.


        Examples:


        An Attribute for an Indicator / Adversary relationship:

        /adversaries/:adversary_id/indicators/:object_link_id/attributes/:object_link_attribute_id


        An Attribute for an Indicator / Indicator relationship:

        /indicators/:indicator_id/indicators/:object_link_id/attributes/:object_link_attribute_id'
      parameters:
      - $ref: '#/components/parameters/SrcObject'
      - $ref: '#/components/parameters/SrcObjectId'
      - $ref: '#/components/parameters/DestObject'
      - $ref: '#/components/parameters/ObjectLinkId'
      - $ref: '#/components/parameters/ObjectLinkAttributeId'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/ObjectLinkAttributeWithRelation'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getBySrcObjectCollectionBySrcObjectIdByDestObjectCollectionByObjectLinkIdAttributesByObjectLinkAttributeId
      x-operation-id-source: derived
    put:
      tags:
      - Object Relationship Attributes
      summary: Update a Relationship Attribute for an Object Type
      description: 'This path can be used for any combination of objects installed on the system.


        Examples:


        An Attribute for an Indicator / Adversary relationship:

        /adversaries/:adversary_id/indicators/:object_link_id/attributes/:object_link_attribute_id


        An Attribute for an Indicator / Indicator relationship:

        /indicators/:indicator_id/indicators/:object_link_id/attributes/:object_link_attribute_id'
      parameters:
      - $ref: '#/components/parameters/SrcObject'
      - $ref: '#/components/parameters/SrcObjectId'
      - $ref: '#/components/parameters/DestObject'
      - $ref: '#/components/parameters/ObjectLinkId'
      - $ref: '#/components/parameters/ObjectLinkAttributeId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectAttributeValue'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/ObjectLinkAttribute'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: putBySrcObjectCollectionBySrcObjectIdByDestObjectCollectionByObjectLinkIdAttributesByObjectLinkAttributeId
      x-operation-id-source: derived
    delete:
      tags:
      - Object Relationship Attributes
      summary: Remove a Relationship Attribute for an Object Type
      description: 'This path can be used for any combination of objects installed on the system.


        Examples:


        An Attribute for an Indicator / Adversary relationship:

        /adversaries/:adversary_id/indicators/:object_link_id/attributes/:object_link_attribute_id


        An Attribute for an Indicator / Indicator relationship:

        /indicators/:indicator_id/indicators/:object_link_id/attributes/:object_link_attribute_id'
      parameters:
      - $ref: '#/components/parameters/SrcObject'
      - $ref: '#/components/parameters/SrcObjectId'
      - $ref: '#/components/parameters/DestObject'
      - $ref: '#/components/parameters/ObjectLinkId'
      - $ref: '#/components/parameters/ObjectLinkAttributeId'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: deleteBySrcObjectCollectionBySrcObjectIdByDestObjectCollectionByObjectLinkIdAttributesByObjectLinkAttributeId
      x-operation-id-source: derived
components:
  parameters:
    DestObject:
      name: dest_object_collection
      in: path
      description: "Destination Object collection - the collection for an object type that may have relationships\n associated with the Source Object collection. Options include: adversaries, attachments, attack_pattern,\n campaign, course_of_action, event, exploit_target, identity, incident, indicators, intrustion_set, malware,\n report, signature, tool, ttp, and vulnerability. If you have any additional custom objects installed on your\n system, use the `object_code` associated with the object definition."
      required: true
      schema:
        type: string
        example: adversaries
    Limit:
      name: limit
      in: query
      description: <br>The number of objects included in the response.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 10
    Sort:
      name: sort
      in: query
      description: "<br>Designate the field(s) you want to use to sort the retrieved list. You can prepend each field \n        with a minus sign (-) to reverse the sorting order. This string can be a list of comma-separated values."
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: id,created_at
    ObjectLinkAttributeId:
      name: object_link_attribute_id
      in: path
      description: Object Link Attribute ID
      required: true
      schema:
        type: integer
        example: 3
    SrcObjectId:
      name: src_object_id
      in: path
      description: Source Object ID - the ID of the object whose relationships you would like to retrieve
      required: true
      schema:
        type: integer
        example: 2
    ObjectLinkId:
      name: object_link_id
      in: path
      description: Object Link ID - the ID of the relationship record
      required: true
      schema:
        type: integer
        example: 3
    SrcObject:
      name: src_object_collection
      in: path
      description: "Source Object collection - the object type collection whose relationships you would like\n to retrieve. Options include: adversaries, attachments, attack_pattern, campaign, course_of_action, event,\n exploit_target, identity, incident, indicators, intrustion_set, malware, report, signature, tool, ttp,\n and vulnerability. If you have any additional custom objects installed on your system, use the `object_code`\n associated with the object definition."
      required: true
      schema:
        type: string
        example: indicators
    Offset:
      name: offset
      in: query
      description: <br>The number of result set records that should be ignored.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 50
  schemas:
    ObjectLinkAttributeWithRelation:
      allOf:
      - properties:
          attribute:
            $ref: '#/components/schemas/Attribute'
        type: object
      - $ref: '#/components/schemas/ObjectLinkAttribute'
    AttributeId:
      properties:
        id:
          description: Attribute ID
          type: integer
          example: 1
      type: object
    ObjectAttributeValue:
      properties:
        value:
          description: Attribute Value
          type: string
          example: High
      type: object
    ObjectLinkAttributeFillable:
      allOf:
      - $ref: '#/components/schemas/AttributeFillable'
      - $ref: '#/components/schemas/ObjectAttributeValue'
    TotalResponse:
      properties:
        total:
          description: Total Number of Objects Processed
          type: integer
          example: 1
      type: object
    ObjectLinkAttribute:
      allOf:
      - properties:
          object_link_id:
            description: Object Link ID
            type: integer
            example: 120
        type: object
      - $ref: '#/components/schemas/ObjectLinkAttributeBasics'
      - $ref: '#/components/schemas/ThreatQTimestamps'
      - $ref: '#/components/schemas/ObjectAttributeValue'
    AttributeFillable:
      properties:
        name:
          description: Attribute Name
          type: string
          example: Confidence
      type: object
    ThreatQTimestamps:
      properties:
        created_at:
          description: Creation Date
          type: string
          example: '2021-07-29 13:58:03'
        updated_at:
          description: Update Date
          type: string
          example: '2022-04-12 08:32:16'
      type: object
    Attribute:
      allOf:
      - $ref: '#/components/schemas/AttributeId'
      - $ref: '#/components/schemas/AttributeFillable'
      - $ref: '#/components/schemas/ThreatQTimestamps'
    ObjectLinkAttributeBasics:
      allOf:
      - properties:
          id:
            description: Object Link Attribute ID
            type: integer
            example: 11
        type: object
      - $ref: '#/components/schemas/ObjectLinkAttributeFillable'
      - $ref: '#/components/schemas/ObjectAttributeValue'
  responses:
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Object Not Found
    NoContent:
      description: Object(s) were successfully deleted.
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
