openapi: 3.2.0
info:
  title: ThreatQ Authentication API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Authentication
paths:
  /token:
    post:
      tags:
      - Authentication
      summary: OAuth2 Authentication
      description: 'You must have a ThreatQ User account to retrieve an API token. The API token is required for all requests. The

        token does time out; therefore, you must periodically refresh the token.


        Before authentication is attempted,

        the Client ID used should be retrieved via GET to `/assets/js/config.js`.


        NOTE: The Authorization header can be ignored as authentication has not occurred yet.'
      operationId: 6dfefacb2109527235856b8df26618d5
      requestBody:
        content:
          application/json:
            schema:
              properties:
                grant_type:
                  description: 'The grant_type you are authenticating with.<br><br>Options include: `password`'
                  type: string
                  example: password
                client_id:
                  description: Client ID retrieved from GET `<hostname>/assets/js/config.js
                  type: string
                  example: ngmwzmvkntc1owe4nmy0mjuyoda0nwq1
                email:
                  description: User's email
                  type: string
                  example: fMercury@threatq.com
                password:
                  description: User's password
                  type: string
                  example: '****************'
              type: object
      responses:
        '200':
          description: Successful Login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Failed Validation
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                      example: User credentials are not valid.
                type: object
        '503':
          $ref: '#/components/responses/MaintenanceMode'
      x-visibility: public
  /logout:
    get:
      tags:
      - Authentication
      summary: Logout
      operationId: 420845c6af8d2584f9ed8aed4babea13
      responses:
        '200':
          $ref: '#/components/responses/Success'
      x-visibility: public
components:
  responses:
    MaintenanceMode:
      description: System is in Maintenance Mode.
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                items:
                  type: string
                  example: ThreatQ is down for maintenance.
            type: object
    Success:
      description: OK
  schemas:
    Token:
      properties:
        access_token:
          description: Access token for future API calls
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
        refresh_token:
          type: string
      type: object
      example:
        access_token: AbCdEfGhIjKLm
        token_type: bearer
        expires_in: 3599
        refresh_token: NoPqRsTuVwXyZ
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
