openapi: 3.2.0
info:
  title: ThreatQ Object Tags API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Object Tags
paths:
  /{object_type}/{object_type_id}/tags:
    get:
      tags:
      - Object Tags
      summary: List Tags for an Object Type
      description: 'This path can be used for any object type installed on the system.


        Examples:


        Indicator Tags: /indicators/:indicator_id/tags


        Attack Pattern Tags: /attack_pattern/:attack_pattern_id/tags'
      parameters:
      - $ref: '#/components/parameters/ObjectType'
      - $ref: '#/components/parameters/ObjectTypeId'
      - $ref: '#/components/parameters/ObjectTagWith'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - properties:
                            id:
                              description: Object Tag ID
                              type: integer
                              example: 81
                            name:
                              description: Tag Name
                              type: string
                              example: Malicious
                          type: object
                        - properties:
                            pivot:
                              $ref: '#/components/schemas/ObjectTagPivot'
                          type: object
                        - properties:
                            indicators:
                              type: array
                              items:
                                allOf:
                                - properties:
                                    pivot:
                                      $ref: '#/components/schemas/ObjectTagPivot'
                                  type: object
                                - $ref: '#/components/schemas/Indicator'
                          type: object
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getByObjectTypeByObjectTypeIdTags
      x-operation-id-source: derived
    post:
      tags:
      - Object Tags
      summary: Create a Tag for an Object Type
      description: 'This path can be used for any object type installed on the system.


        Examples:


        Indicator Tags: /indicators/:indicator_id/tags


        Attack Pattern Tags: /attack_pattern/:attack_pattern_id/tags'
      parameters:
      - $ref: '#/components/parameters/ObjectType'
      - $ref: '#/components/parameters/ObjectTypeId'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TagFillable'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - properties:
                            pivot:
                              $ref: '#/components/schemas/ObjectTagPivot'
                          type: object
                        - $ref: '#/components/schemas/Tag'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
      operationId: postByObjectTypeByObjectTypeIdTags
      x-operation-id-source: derived
  /{object_type}/{object_type_id}/tags/{object_type_tag_id}:
    get:
      tags:
      - Object Tags
      summary: Get a Single Tag for an Object Type
      description: 'This path can be used for any object type installed on the system.


        Examples:


        Indicator Tags: /indicators/:indicator_id/tags/:indicator_tag_id


        Attack Pattern Tags: /attack_pattern/:attack_pattern_id/tags/:attack_pattern_tag_id'
      parameters:
      - $ref: '#/components/parameters/ObjectType'
      - $ref: '#/components/parameters/ObjectTypeId'
      - $ref: '#/components/parameters/ObjectTypeTagId'
      - $ref: '#/components/parameters/ObjectTagWith'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - properties:
                            id:
                              description: Object Tag ID
                              type: integer
                              example: 81
                            name:
                              description: Tag Name
                              type: string
                              example: Malicious
                          type: object
                        - properties:
                            pivot:
                              $ref: '#/components/schemas/ObjectTagPivot'
                          type: object
                        - properties:
                            indicators:
                              type: array
                              items:
                                allOf:
                                - properties:
                                    pivot:
                                      $ref: '#/components/schemas/ObjectTagPivot'
                                  type: object
                                - $ref: '#/components/schemas/Indicator'
                          type: object
                  type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getByObjectTypeByObjectTypeIdTagsByObjectTypeTagId
      x-operation-id-source: derived
    delete:
      tags:
      - Object Tags
      summary: Delete a Tag for an Object Type
      description: 'This path can be used for any object type installed on the system.


        Examples:


        Indicator Tags: /indicators/:indicator_id/tags/:indicator_tag_id


        Attack Pattern Tags: /attack_pattern/:attack_pattern_id/tags/:indicator_tag_id'
      parameters:
      - $ref: '#/components/parameters/ObjectType'
      - $ref: '#/components/parameters/ObjectTypeId'
      - $ref: '#/components/parameters/ObjectTypeTagId'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: deleteByObjectTypeByObjectTypeIdTagsByObjectTypeTagId
      x-operation-id-source: derived
components:
  schemas:
    Tag:
      allOf:
      - properties:
          id:
            description: Tag ID
            type: integer
            example: 81
        type: object
      - $ref: '#/components/schemas/TagFillable'
    TotalResponse:
      properties:
        total:
          description: Total Number of Objects Processed
          type: integer
          example: 1
      type: object
    ThreatQTimestamps:
      properties:
        created_at:
          description: Creation Date
          type: string
          example: '2021-07-29 13:58:03'
        updated_at:
          description: Update Date
          type: string
          example: '2022-04-12 08:32:16'
      type: object
    IndicatorFillable:
      properties:
        type_id:
          description: Indicator Type ID
          type: integer
          example: 11
        status_id:
          description: Indicator Status ID
          type: integer
          example: 2
        class:
          description: 'Indicator Class - Options include: host, network'
          type: string
          example: network
        value:
          description: Indicator Value
          type: string
          example: www.danger-doom.com
        description:
          description: Indicator Description
          type: string
          example: Website encountered during incident investigation.
      type: object
    Indicator:
      allOf:
      - properties:
          id:
            description: Indicator ID
            type: integer
            example: 54
        type: object
      - properties:
          hash:
            description: Indicator Hash
            type: string
            example: 4aba5ab07a3bda558d5d725a09d93ba6
          last_detected_at:
            description: Date the Indicator was last encountered
            type: string
            example: '2020-02-28 13:42:51'
          expires_at:
            description: Date the Indicator will expire
            type: string
            example: '2020-04-01 03:17:23'
          expired_at:
            description: Date the Indicator expired
            type: string
            example: null
          expired_needs_calc:
            description: Determines whether the Indicator's expiration date needs updating
            type: string
            example: N
          expires_calculated_at:
            description: Date the Indicator's expiration date was calculated
            type: string
            example: '2020-02-28 18:36:24'
        type: object
      - $ref: '#/components/schemas/IndicatorFillable'
      - $ref: '#/components/schemas/ThreatQTimestamps'
      - $ref: '#/components/schemas/TouchedAtTimestamp'
    TouchedAtTimestamp:
      properties:
        touched_at:
          description: Update Date for Object Context (Attributes, Comments, Sources, Relationships)
          type: string
          example: '2021-11-13 15:28:17'
      type: object
    TagFillable:
      properties:
        name:
          description: Tag Name
          type: string
          example: Ominous
      type: object
    ObjectTagPivot:
      allOf:
      - properties:
          tag_id:
            description: Tag ID
            type: integer
            example: 81
          object_id:
            description: Object ID
            type: integer
            example: 3
        type: object
      - $ref: '#/components/schemas/ThreatQTimestamps'
  responses:
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Object Not Found
    NoContent:
      description: Object(s) were successfully deleted.
  parameters:
    Limit:
      name: limit
      in: query
      description: <br>The number of objects included in the response.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 10
    ObjectTagWith:
      name: with
      in: query
      description: "<br>Object Relationships that can be included in the response.<br><br>Options include: `<object_collection>`\n  <br><br>The `<object_collection>` placeholder in the options takes the value of the `collection` field for an object definition.<br><br>"
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          example: indicators
    ObjectTypeId:
      name: object_type_id
      in: path
      description: The ID for the record of the specified Object Type whose context you would like to retrieve
      required: true
      schema:
        type: integer
        example: 6
    ObjectType:
      name: object_type
      in: path
      description: 'The collection identifier for the Object Type whose context you would like to retrieve. Options include:

        adversaries, attachments, attack_pattern, campaign, course_of_action, event, exploit_target, identity, incident,

        indicators, intrustion_set, malware, report, signature, tool, ttp, and vulnerability. If you have any additional custom

        objects installed on your system, use the value for the `collection` field associated with the object definition.'
      required: true
      schema:
        type: string
        example: indicators
    Offset:
      name: offset
      in: query
      description: <br>The number of result set records that should be ignored.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 50
    Sort:
      name: sort
      in: query
      description: "<br>Designate the field(s) you want to use to sort the retrieved list. You can prepend each field \n        with a minus sign (-) to reverse the sorting order. This string can be a list of comma-separated values."
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: id,created_at
    ObjectTypeTagId:
      name: object_type_tag_id
      in: path
      description: The ID of the Tag record for the specified Object Type
      required: true
      schema:
        type: integer
        example: 1
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
