openapi: 3.2.0
info:
  title: ThreatQ System API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: System
paths:
  /system/license:
    get:
      tags:
      - System
      summary: Get the System License
      operationId: 32f229da5ee3969d6bbfd3683d2d9ceb
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/License'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
  /system/time-zone:
    get:
      tags:
      - System
      summary: Get the System Time Zone
      operationId: a9ff3d1c98efd062c854eff642b37143
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    description: Configured Time Zone for the System
                    type: string
                    example: UTC
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
components:
  responses:
    Unauthorized:
      description: Unauthorized
  schemas:
    License:
      properties:
        customer:
          description: Customer Name
          type: string
          example: TQ Dev
        user-limit:
          description: Number of Users included with License
          type: integer
          example: 10
        expires:
          description: License Expiration Date
          type: string
          example: '2021-04-15 15:04:48'
        features:
          description: Application Features included in the License
          type: object
          example:
            investigations: '2021-04-15 15:04:48'
      type: object
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
