openapi: 3.2.0
info:
  title: ThreatQ Object Attribute Sources API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Object Attribute Sources
paths:
  /{object_type}/{object_type_id}/attributes/{object_type_attribute_id}/sources/{object_type_attribute_source_id}:
    put:
      tags:
      - Object Attribute Sources
      summary: Update an Attribute Source for an Object Type
      description: 'This path can be used for any object type installed on the system.


        Examples:


        Indicator Attribute Sources:

        /indicators/:indicator_id/attributes/:indicator_attribute_id/sources/:indicator_attribute_source_id


        Attack Pattern Sources:

        /attack_pattern/:attack_pattern_id/attributes/:attack_pattern_attribute_id/sources/:attack_pattern_attribute_source_id'
      parameters:
      - $ref: '#/components/parameters/ObjectType'
      - $ref: '#/components/parameters/ObjectTypeId'
      - $ref: '#/components/parameters/ObjectTypeAttributeId'
      - $ref: '#/components/parameters/ObjectTypeAttributeSourceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TLPRequestOptions'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ObjectAttributeSource'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: putByObjectTypeByObjectTypeIdAttributesByObjectTypeAttributeIdSourcesByObjectTypeAttributeSourceId
      x-operation-id-source: derived
    delete:
      tags:
      - Object Attribute Sources
      summary: Remove an Attribute Source for an Object Type
      description: 'This path can be used for any object type installed on the system.


        Examples:


        Indicator Attribute Sources:

        /indicators/:indicator_id/attributes/:indicator_attribute_id/sources/:indicator_attribute_source_id


        Attack Pattern Sources:

        /attack_pattern/:attack_pattern_id/attributes/:attack_pattern_attribute_id/sources/:attack_pattern_attribute_source_id'
      parameters:
      - $ref: '#/components/parameters/ObjectType'
      - $ref: '#/components/parameters/ObjectTypeId'
      - $ref: '#/components/parameters/ObjectTypeAttributeId'
      - $ref: '#/components/parameters/ObjectTypeAttributeSourceId'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: deleteByObjectTypeByObjectTypeIdAttributesByObjectTypeAttributeIdSourcesByObjectTypeAttributeSourceId
      x-operation-id-source: derived
components:
  schemas:
    CreatorSource:
      properties:
        creator_source_id:
          description: Creator Source ID - Source ID of User, Feed, or other means that brought the object into the system
          type: integer
          example: 2
      type: object
    ThreatQTimestamps:
      properties:
        created_at:
          description: Creation Date
          type: string
          example: '2021-07-29 13:58:03'
        updated_at:
          description: Update Date
          type: string
          example: '2022-04-12 08:32:16'
      type: object
    PublishedAtTimestamp:
      properties:
        published_at:
          description: Publish Date for Object (Date it was first reported by the Source)
          type: string
          example: '2017-01-13 15:28:17'
      type: object
    ObjectSourceId:
      properties:
        source_id:
          description: Source ID
          type: integer
          example: 42
      type: object
    ObjectTypeAttributeId:
      properties:
        <object_type>_attribute_id:
          description: "Object Type Attribute ID - `<object_type>` should be replaced with the Object Type `code` field. This field will match the\n Object Type collection specified in the URL path.<br><br>Example: indicator_attribute_id"
          type: integer
          example: 7
      type: object
    ObjectAttributeSource:
      allOf:
      - properties:
          id:
            description: Object Type Source ID
            type: integer
            example: 42
          tlp_id:
            description: TLP ID
            type: integer
            example: 1
        type: object
      - $ref: '#/components/schemas/ObjectTypeAttributeId'
      - $ref: '#/components/schemas/ObjectSourceId'
      - $ref: '#/components/schemas/CreatorSource'
      - $ref: '#/components/schemas/ThreatQTimestamps'
      - $ref: '#/components/schemas/PublishedAtTimestamp'
    TLPRequestOptions:
      oneOf:
      - properties:
          tlp_id:
            description: Source TLP ID
            type: integer
            example: 3
        type: object
      - properties:
          tlp:
            $ref: '#/components/schemas/TLPName'
        type: object
    TLPName:
      properties:
        name:
          description: TLP Name
          type: string
          example: WHITE
      type: object
  responses:
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Object Not Found
    NoContent:
      description: Object(s) were successfully deleted.
  parameters:
    ObjectTypeAttributeSourceId:
      name: object_type_attribute_source_id
      in: path
      description: The ID of the Attribute Source record for the specified Object Type
      required: true
      schema:
        type: integer
        example: 5
    ObjectTypeId:
      name: object_type_id
      in: path
      description: The ID for the record of the specified Object Type whose context you would like to retrieve
      required: true
      schema:
        type: integer
        example: 6
    ObjectType:
      name: object_type
      in: path
      description: 'The collection identifier for the Object Type whose context you would like to retrieve. Options include:

        adversaries, attachments, attack_pattern, campaign, course_of_action, event, exploit_target, identity, incident,

        indicators, intrustion_set, malware, report, signature, tool, ttp, and vulnerability. If you have any additional custom

        objects installed on your system, use the value for the `collection` field associated with the object definition.'
      required: true
      schema:
        type: string
        example: indicators
    ObjectTypeAttributeId:
      name: object_type_attribute_id
      in: path
      description: The ID of the Attribute record for the specified Object Type
      required: true
      schema:
        type: integer
        example: 3
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
