openapi: 3.2.0
info:
  title: ThreatQ Tags API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Tags
paths:
  /tags:
    get:
      tags:
      - Tags
      summary: List Tags
      operationId: eeb07c6c23256852e6319158d6ad1eff
      parameters:
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/TagWith'
      - $ref: '#/components/parameters/TagWithObjects'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/TagWithRelationships'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
  /tags/{tag_id}{?with}:
    get:
      tags:
      - Tags
      summary: Get a Single Tag
      parameters:
      - $ref: '#/components/parameters/TagId'
      - $ref: '#/components/parameters/TagWith'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TagWithRelationships'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getTagsByTagId}{?with
      x-operation-id-source: derived
components:
  schemas:
    CourseOfActionTag:
      allOf:
      - properties:
          pivot:
            $ref: '#/components/schemas/TagPivot'
        type: object
      - $ref: '#/components/schemas/CourseOfAction'
    IndicatorTag:
      allOf:
      - properties:
          pivot:
            $ref: '#/components/schemas/TagPivot'
        type: object
      - $ref: '#/components/schemas/Indicator'
    TotalResponse:
      properties:
        total:
          description: Total Number of Objects Processed
          type: integer
          example: 1
      type: object
    IndicatorFillable:
      properties:
        type_id:
          description: Indicator Type ID
          type: integer
          example: 11
        status_id:
          description: Indicator Status ID
          type: integer
          example: 2
        class:
          description: 'Indicator Class - Options include: host, network'
          type: string
          example: network
        value:
          description: Indicator Value
          type: string
          example: www.danger-doom.com
        description:
          description: Indicator Description
          type: string
          example: Website encountered during incident investigation.
      type: object
    AdversaryFillable:
      properties:
        name:
          description: Adversary Name
          type: string
          example: Sad Panda
      type: object
    TagFillable:
      properties:
        name:
          description: Tag Name
          type: string
          example: Ominous
      type: object
    Adversary:
      allOf:
      - properties:
          id:
            description: Adversary ID
            type: integer
            example: 54
        type: object
      - $ref: '#/components/schemas/AdversaryFillable'
      - $ref: '#/components/schemas/ThreatQTimestamps'
      - $ref: '#/components/schemas/TouchedAtTimestamp'
    ThreatQTimestamps:
      properties:
        created_at:
          description: Creation Date
          type: string
          example: '2021-07-29 13:58:03'
        updated_at:
          description: Update Date
          type: string
          example: '2022-04-12 08:32:16'
      type: object
    TagPivot:
      allOf:
      - properties:
          tag_id:
            description: Tag ID
            type: integer
            example: 1
          object_id:
            description: Object ID
            type: integer
            example: 54
        type: object
      - $ref: '#/components/schemas/ThreatQTimestamps'
    AdversaryTag:
      allOf:
      - properties:
          pivot:
            $ref: '#/components/schemas/TagPivot'
        type: object
      - $ref: '#/components/schemas/Adversary'
    CourseOfAction:
      allOf:
      - properties:
          id:
            description: Course of Action ID
            type: integer
            example: 6274
        type: object
      - $ref: '#/components/schemas/CourseOfActionFillable'
      - $ref: '#/components/schemas/ThreatQTimestamps'
      - $ref: '#/components/schemas/TouchedAtTimestamp'
    CourseOfActionFillable:
      properties:
        value:
          description: Course of Action Value
          type: string
          example: TXXXX - Account Discovery Mitigation
        description:
          description: Description for the Course of Action
          type: string
          example: Prevent administrator accounts from...
      type: object
    TagWithRelationships:
      allOf:
      - properties:
          adversaries:
            type: array
            items:
              $ref: '#/components/schemas/AdversaryTag'
          indicators:
            type: array
            items:
              $ref: '#/components/schemas/IndicatorTag'
          course_of_action:
            type: array
            items:
              $ref: '#/components/schemas/CourseOfActionTag'
        type: object
      - $ref: '#/components/schemas/Tag'
    Tag:
      allOf:
      - properties:
          id:
            description: Tag ID
            type: integer
            example: 81
        type: object
      - $ref: '#/components/schemas/TagFillable'
    Indicator:
      allOf:
      - properties:
          id:
            description: Indicator ID
            type: integer
            example: 54
        type: object
      - properties:
          hash:
            description: Indicator Hash
            type: string
            example: 4aba5ab07a3bda558d5d725a09d93ba6
          last_detected_at:
            description: Date the Indicator was last encountered
            type: string
            example: '2020-02-28 13:42:51'
          expires_at:
            description: Date the Indicator will expire
            type: string
            example: '2020-04-01 03:17:23'
          expired_at:
            description: Date the Indicator expired
            type: string
            example: null
          expired_needs_calc:
            description: Determines whether the Indicator's expiration date needs updating
            type: string
            example: N
          expires_calculated_at:
            description: Date the Indicator's expiration date was calculated
            type: string
            example: '2020-02-28 18:36:24'
        type: object
      - $ref: '#/components/schemas/IndicatorFillable'
      - $ref: '#/components/schemas/ThreatQTimestamps'
      - $ref: '#/components/schemas/TouchedAtTimestamp'
    TouchedAtTimestamp:
      properties:
        touched_at:
          description: Update Date for Object Context (Attributes, Comments, Sources, Relationships)
          type: string
          example: '2021-11-13 15:28:17'
      type: object
  parameters:
    Limit:
      name: limit
      in: query
      description: <br>The number of objects included in the response.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 10
    Sort:
      name: sort
      in: query
      description: "<br>Designate the field(s) you want to use to sort the retrieved list. You can prepend each field \n        with a minus sign (-) to reverse the sorting order. This string can be a list of comma-separated values."
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: id,created_at
    TagId:
      name: tag_id
      in: path
      description: Tag ID
      required: true
      schema:
        type: integer
    TagWithObjects:
      name: with_DUPLICATES_PREVIOUS_NAME
      in: query
      description: <br>Related Object IDs (as opposed to full Object models) that can be included in the response.
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: objects
    Offset:
      name: offset
      in: query
      description: <br>The number of result set records that should be ignored.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 50
    TagWith:
      name: with
      in: query
      description: "<br>Related Object models that can be included in the response.<br><br>Options include: adversaries, \nattachments, attack_pattern, campaign, course_of_action, events, exploit_target, identity, incident, indicators,\nintrusion_set, malware, recipient, report, signatures, tool, and ttp."
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: adversaries,indicators,course_of_action
  responses:
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Object Not Found
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
