openapi: 3.2.0
info:
  title: ThreatQ TLP API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: TLP
paths:
  /tlp:
    post:
      tags:
      - TLP
      summary: Create a TLP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TLPFillable'
      responses:
        '201':
          description: New TLP Created
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TLP'
                type: object
        '400':
          $ref: '#/components/responses/FailedValidation'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
      operationId: postTlp
      x-operation-id-source: derived
  /tlp/{tlp_id}:
    get:
      tags:
      - TLP
      summary: Get a Single TLP
      parameters:
      - $ref: '#/components/parameters/TLPId'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TLP'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getTlpByTlpId
      x-operation-id-source: derived
    put:
      tags:
      - TLP
      summary: Update a TLP
      parameters:
      - $ref: '#/components/parameters/TLPId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TLPFillable'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TLP'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: putTlpByTlpId
      x-operation-id-source: derived
    delete:
      tags:
      - TLP
      summary: Delete a TLP
      parameters:
      - $ref: '#/components/parameters/TLPId'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: deleteTlpByTlpId
      x-operation-id-source: derived
  /tlp{?limit,offset,sort}:
    get:
      tags:
      - TLP
      summary: List TLPs
      parameters:
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/TLP'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
      operationId: getTlp{?limit,offset,sort}
      x-operation-id-source: derived
components:
  responses:
    Unauthorized:
      description: Unauthorized
    FailedValidation:
      description: Validation Failed
    NotFound:
      description: Object Not Found
    NoContent:
      description: Object(s) were successfully deleted.
  schemas:
    TotalResponse:
      properties:
        total:
          description: Total Number of Objects Processed
          type: integer
          example: 1
      type: object
    TLPFillable:
      allOf:
      - properties:
          name:
            description: TLP Name
            type: string
            example: WHITE
          description:
            description: TLP Description
            type: string
            example: Disclosure is not limited.
          value:
            description: TLP Value used for hierarchy comparisons
            type: integer
            example: 3
          user_editable:
            description: Determines whether the TLP record can be updated by a User
            type: string
            example: N
        type: object
      - $ref: '#/components/schemas/TLPName'
    TLPName:
      properties:
        name:
          description: TLP Name
          type: string
          example: WHITE
      type: object
    TLP:
      allOf:
      - properties:
          id:
            description: TLP ID
            type: integer
            example: 1
        type: object
      - properties:
          created_at:
            description: TLP Creation Date
            type: string
            example: '2020-05-01 02:35:16'
          updated_at:
            description: TLP Update Date
            type: string
            example: '2020-05-03 04:27:51'
        type: object
      - $ref: '#/components/schemas/TLPFillable'
  parameters:
    Limit:
      name: limit
      in: query
      description: <br>The number of objects included in the response.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 10
    TLPId:
      name: tlp_id
      in: path
      description: TLP ID
      required: true
      schema:
        type: integer
    Offset:
      name: offset
      in: query
      description: <br>The number of result set records that should be ignored.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 50
    Sort:
      name: sort
      in: query
      description: "<br>Designate the field(s) you want to use to sort the retrieved list. You can prepend each field \n        with a minus sign (-) to reverse the sorting order. This string can be a list of comma-separated values."
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: id,created_at
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
