openapi: 3.2.0
info:
  title: ThreatQ Basic Search API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Basic Search
paths:
  /all/attributes/search:
    get:
      tags:
      - Basic Search
      summary: Attribute Search
      description: Get attributes matching the specified search query
      operationId: ef800ae5e0fae452a1d00f54594ab4b1
      parameters:
      - $ref: '#/components/parameters/BasicSearchQuery'
      - $ref: '#/components/parameters/BasicSearchLimit'
      - $ref: '#/components/parameters/BasicSearchWith'
      responses:
        '200':
          $ref: '#/components/responses/SearchAttribute'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
  /all/tags/search:
    get:
      tags:
      - Basic Search
      summary: Tag Search
      description: Get tags matching the specified search query
      operationId: 595d29069b3d3b5b8c6e799da0b4cab7
      parameters:
      - $ref: '#/components/parameters/BasicSearchQuery'
      - $ref: '#/components/parameters/BasicSearchLimit'
      - $ref: '#/components/parameters/BasicSearchWith'
      responses:
        '200':
          $ref: '#/components/responses/SearchTag'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
  /search:
    get:
      tags:
      - Basic Search
      summary: Object Search
      description: Get objects matching the specified search query
      operationId: afadbbd422590b1ee4160409aee46dc8
      parameters:
      - $ref: '#/components/parameters/BasicSearchQuery'
      - $ref: '#/components/parameters/BasicSearchLimit'
      - $ref: '#/components/parameters/BasicSearchWith'
      responses:
        '200':
          $ref: '#/components/responses/SearchObject'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
components:
  responses:
    Unauthorized:
      description: Unauthorized
    SearchTag:
      description: Request Successful
      content:
        application/json:
          schema:
            properties:
              data:
                description: Listing of search tags
                type: array
                items:
                  $ref: '#/components/schemas/SearchTag'
            type: object
    SearchObject:
      description: Request Successful
      content:
        application/json:
          schema:
            properties:
              data:
                description: Listing of search objects
                type: array
                items:
                  $ref: '#/components/schemas/SearchObject'
            type: object
    SearchAttribute:
      description: Request Successful
      content:
        application/json:
          schema:
            properties:
              data:
                description: Listing of search attributes
                type: array
                items:
                  $ref: '#/components/schemas/SearchAttribute'
            type: object
  schemas:
    SearchTag:
      properties:
        tag_id:
          description: Tag id
          type: integer
          example: 1
        object_id:
          description: Object id
          type: integer
          example: 1
        type:
          description: Object type<br /><br /><b>Note:</b> Any created custom object name can be used
          type: string
          enum:
          - adversary
          - attachment
          - attack_pattern
          - campaign
          - course_of_action
          - event
          - exploit_target
          - identity
          - incident
          - indicator
          - intrusion_set
          - investigation
          - malware
          - report
          - signature
          - task
          - tool
          - ttp
          - vulnerability
          example: indicator
        name:
          description: Tag name
          type: string
          example: www.threatquotient.com
      type: object
    ObjectType:
      description: Object type<br /><br /><b>Note:</b> Any created custom object name can be used
      type: string
      enum:
      - adversary
      - attachment
      - attack_pattern
      - campaign
      - course_of_action
      - event
      - exploit_target
      - identity
      - incident
      - indicator
      - intrusion_set
      - investigation
      - malware
      - report
      - signature
      - task
      - tool
      - ttp
      - vulnerability
      example: indicator
    SearchObject:
      properties:
        id:
          description: Object id
          type: integer
          example: 1
        type:
          $ref: '#/components/schemas/ObjectType'
        value:
          description: Object value
          type: string
          example: www.threatquotient.com
      type: object
    SearchAttribute:
      properties:
        object_attribute_id:
          description: Object attribute id
          type: integer
          example: 1
        type:
          description: Object type<br /><br /><b>Note:</b> Any created custom object name can be used
          type: string
          enum:
          - adversary
          - attachment
          - attack_pattern
          - campaign
          - course_of_action
          - event
          - exploit_target
          - identity
          - incident
          - indicator
          - intrusion_set
          - investigation
          - malware
          - report
          - signature
          - task
          - tool
          - ttp
          - vulnerability
          example: indicator
        object_id:
          description: Object id
          type: integer
          example: 1
        attribute_id:
          description: Attribute id
          type: integer
          example: 1
        value:
          description: Attribute value
          type: string
          example: www.threatquotient.com
      type: object
  parameters:
    BasicSearchLimit:
      name: limit
      in: query
      description: <br />Number of objects included in the response.
      required: false
      schema:
        type: integer
        default: 30
        example: 10
    BasicSearchWith:
      name: with
      in: query
      description: <br />Comma-delimited list of primary and/or custom objects to be applied to the query.
      required: false
      schema:
        type: string
        default: all
        example: indicators,malware
    BasicSearchQuery:
      name: query
      in: query
      description: <br />Search value to be applied to the query.
      required: true
      schema:
        type: string
        example: www.threatquotient.com
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
