openapi: 3.2.0
info:
  title: ThreatQ Object Relation Counts API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Object Relation Counts
paths:
  /{object_type}/{object_type_id}/relation-counts:
    get:
      tags:
      - Object Relation Counts
      summary: List Relation Counts for an Object Type
      description: 'This path can be used for any object type installed on the system.


        Examples:


        Indicator Sources: /indicators/:indicator_id/relation-counts


        Attack Pattern Sources: /attack_pattern/:attack_pattern_id/relation-counts'
      parameters:
      - $ref: '#/components/parameters/ObjectType'
      - $ref: '#/components/parameters/ObjectTypeId'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    properties:
                      indicators:
                        description: Number of Indicators related to the object
                        type: integer
                        example: 51
                      adversaries:
                        description: Number of Adversaries related to the object
                        type: integer
                        example: 2
                      events:
                        description: Number of Events related to the object
                        type: integer
                        example: 7
                      attachments:
                        description: Number of Attachments (Files) related to the object
                        type: integer
                        example: 11
                      signatures:
                        description: Number of Signatures related to the object
                        type: integer
                        example: 3
                      investigations:
                        description: Number of Investigations related to the object
                        type: integer
                        example: 6
                      attack_pattern:
                        description: Number of Attack Patterns related to the object
                        type: integer
                        example: 17
                      campaign:
                        description: Number of Campaigns related to the object
                        type: integer
                        example: 1
                      course_of_action:
                        description: Number of Courses of Action related to the object
                        type: integer
                        example: 3
                      exploit_target:
                        description: Number of Exploit Targets related to the object
                        type: integer
                        example: 4
                      identity:
                        description: Number of Identities related to the object
                        type: integer
                        example: 2
                      incident:
                        description: Number of Incidents related to the object
                        type: integer
                        example: 512
                      intrusion_set:
                        description: Number of Intrusion Sets related to the object
                        type: integer
                        example: 5
                      malware:
                        description: Number of Malware related to the object
                        type: integer
                        example: 13
                      report:
                        description: Number of Reports related to the object
                        type: integer
                        example: 3
                      tool:
                        description: Number of Tools related to the object
                        type: integer
                        example: 2
                      ttp:
                        description: Number of TTP related to the object
                        type: integer
                        example: 10
                      vulnerability:
                        description: Number of Vulnerability related to the object
                        type: integer
                        example: 11
                    type: object
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getByObjectTypeByObjectTypeIdRelationCounts
      x-operation-id-source: derived
components:
  responses:
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Object Not Found
  parameters:
    ObjectTypeId:
      name: object_type_id
      in: path
      description: The ID for the record of the specified Object Type whose context you would like to retrieve
      required: true
      schema:
        type: integer
        example: 6
    ObjectType:
      name: object_type
      in: path
      description: 'The collection identifier for the Object Type whose context you would like to retrieve. Options include:

        adversaries, attachments, attack_pattern, campaign, course_of_action, event, exploit_target, identity, incident,

        indicators, intrustion_set, malware, report, signature, tool, ttp, and vulnerability. If you have any additional custom

        objects installed on your system, use the value for the `collection` field associated with the object definition.'
      required: true
      schema:
        type: string
        example: indicators
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
