openapi: 3.2.0
info:
  title: ThreatQ Tool API
  description: '© 2025


    The API doc you are viewing is a BETA version that provides an early look at ThreatQ’s new API documentation format.'
  license:
    name: null
    url: null
  version: 1.0.0
  x-logo:
    url: null
    backgroundColor: null
    altText: ThreatQuotient
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/securonix-b7a/ThreatQ/1.0.0
- url: https://threatq.com/api
  description: ThreatQ Server
security:
- BearerAuth: []
tags:
- name: Tool
paths:
  /tool:
    get:
      tags:
      - Tool
      summary: List Tool
      parameters:
      - $ref: '#/components/parameters/CommonObjectWith'
      - $ref: '#/components/parameters/Sort'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/Tool'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
      operationId: getTool
      x-operation-id-source: derived
    post:
      tags:
      - Tool
      summary: Create a(n) Tool
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                allOf:
                - properties:
                    attributes:
                      type: array
                      items:
                        $ref: '#/components/schemas/AttributeBasics'
                    sources:
                      type: array
                      items:
                        $ref: '#/components/schemas/SourceBasics'
                  type: object
                - $ref: '#/components/schemas/ToolFillable'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - properties:
                            attributes:
                              type: array
                              items:
                                $ref: '#/components/schemas/AttributeBasics'
                            sources:
                              type: array
                              items:
                                $ref: '#/components/schemas/SourceBasics'
                          type: object
                        - $ref: '#/components/schemas/Tool'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
      operationId: postTool
      x-operation-id-source: derived
  /tool/consume:
    post:
      tags:
      - Tool
      summary: Tool Consume
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                allOf:
                - properties:
                    tool:
                      description: Related Tool
                      type: array
                      items:
                        $ref: '#/components/schemas/ToolFillable'
                  type: object
                - $ref: '#/components/schemas/ToolFillable'
                - $ref: '#/components/schemas/CommonObjectConsumeRequest'
      responses:
        '201':
          description: Ingestion Completed Successfully
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - properties:
                            id:
                              description: Tool ID
                              type: integer
                              default: 1
                          type: object
                        - $ref: '#/components/schemas/ToolFillable'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-visibility: public
      operationId: postToolConsume
      x-operation-id-source: derived
  /tool/{tool_id}:
    get:
      tags:
      - Tool
      summary: Get Single Tool
      parameters:
      - $ref: '#/components/parameters/ToolId'
      - $ref: '#/components/parameters/CommonObjectWith'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/Tool'
                type: object
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: getToolByToolId
      x-operation-id-source: derived
    put:
      tags:
      - Tool
      summary: Update a(n) Tool
      parameters:
      - $ref: '#/components/parameters/ToolId'
      - $ref: '#/components/parameters/CommonObjectWith'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                allOf:
                - properties:
                    attributes:
                      type: array
                      items:
                        $ref: '#/components/schemas/AttributeBasics'
                    sources:
                      type: array
                      items:
                        $ref: '#/components/schemas/SourceBasics'
                  type: object
                - $ref: '#/components/schemas/ToolFillable'
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - properties:
                            attributes:
                              type: array
                              items:
                                $ref: '#/components/schemas/AttributeBasics'
                            sources:
                              type: array
                              items:
                                $ref: '#/components/schemas/SourceBasics'
                          type: object
                        - $ref: '#/components/schemas/Tool'
                  type: object
                - $ref: '#/components/schemas/TotalResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: putToolByToolId
      x-operation-id-source: derived
    delete:
      tags:
      - Tool
      summary: Delete Tool
      parameters:
      - $ref: '#/components/parameters/ToolId'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      x-visibility: public
      operationId: deleteToolByToolId
      x-operation-id-source: derived
components:
  parameters:
    ToolId:
      name: tool_id
      in: path
      description: Tool ID
      required: true
      schema:
        type: integer
    Limit:
      name: limit
      in: query
      description: <br>The number of objects included in the response.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 10
    CommonObjectWith:
      name: with
      in: query
      description: '<br>Object Relationships that can be included in the response.<br><br>Options include: adversaries, asset,

        attachments, attack_pattern, attributes, campaign, comments, course_of_action, events, exploit_target, identity,

        incident, indicators, intrusion_set, malware, recipient, report, plugins, pluginActions, signatures, sources, tags,

        tool, ttp, and watchlist.'
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          example: adversaries,comments,sources
    Sort:
      name: sort
      in: query
      description: "<br>Designate the field(s) you want to use to sort the retrieved list. You can prepend each field \n        with a minus sign (-) to reverse the sorting order. This string can be a list of comma-separated values."
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: id,created_at
    Offset:
      name: offset
      in: query
      description: <br>The number of result set records that should be ignored.
      required: false
      style: form
      explode: false
      schema:
        type: integer
        example: 50
  schemas:
    TLPName:
      properties:
        name:
          description: TLP Name
          type: string
          example: WHITE
      type: object
    ObjectAttributeValue:
      properties:
        value:
          description: Attribute Value
          type: string
          example: High
      type: object
    ObjectLinkAttributeFillable:
      allOf:
      - $ref: '#/components/schemas/AttributeFillable'
      - $ref: '#/components/schemas/ObjectAttributeValue'
    TotalResponse:
      properties:
        total:
          description: Total Number of Objects Processed
          type: integer
          example: 1
      type: object
    AttributeBasics:
      allOf:
      - properties:
          sources:
            type: array
            items:
              $ref: '#/components/schemas/SourceBasics'
        type: object
      - $ref: '#/components/schemas/ObjectLinkAttributeFillable'
    AttributeFillable:
      properties:
        name:
          description: Attribute Name
          type: string
          example: Confidence
      type: object
    ThreatQTimestamps:
      properties:
        created_at:
          description: Creation Date
          type: string
          example: '2021-07-29 13:58:03'
        updated_at:
          description: Update Date
          type: string
          example: '2022-04-12 08:32:16'
      type: object
    SourceName:
      properties:
        name:
          description: Source Name
          type: string
          example: ThreatQ
      type: object
    Tool:
      allOf:
      - properties:
          id:
            description: Tool ID
            type: integer
            example: 4781
        type: object
      - $ref: '#/components/schemas/ToolFillable'
      - $ref: '#/components/schemas/ThreatQTimestamps'
      - $ref: '#/components/schemas/TouchedAtTimestamp'
    TouchedAtTimestamp:
      properties:
        touched_at:
          description: Update Date for Object Context (Attributes, Comments, Sources, Relationships)
          type: string
          example: '2021-11-13 15:28:17'
      type: object
    CommonObjectConsumeRequest:
      properties:
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeBasics'
        sources:
          type: array
          items:
            $ref: '#/components/schemas/SourceBasics'
        tlp:
          $ref: '#/components/schemas/TLPName'
        <object_code>:
          description: 'Relate objects of other types by providing a list of IDs. Replace the `<object_code>` property key with

            one of the options to relate objects of that type. <br><br> NOTE: Objects must be created separately before IDs can be

            used in request. <br><br>Options include: adversaries, attachments, attack_pattern, campaign, course_of_action, events,

            exploit_target, identity, incident, indicators, intrusion_set, malware, recipient, report, signatures, tool, ttp.'
          type: array
          items:
            type: integer
            example: 2
      type: object
    SourceBasics:
      oneOf:
      - allOf:
        - properties:
            tlp_id:
              description: Source TLP ID
              type: integer
              example: 3
          type: object
        - $ref: '#/components/schemas/SourceName'
      - allOf:
        - properties:
            tlp:
              $ref: '#/components/schemas/TLPName'
          type: object
        - $ref: '#/components/schemas/SourceName'
    ToolFillable:
      properties:
        value:
          description: Tool Value
          type: string
          example: Ping
        description:
          description: Description for the Tool
          type: string
          example: Ping is an operating system utility commonly used to troubleshoot...
      type: object
  responses:
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Object Not Found
    NoContent:
      description: Object(s) were successfully deleted.
  securitySchemes:
    BearerAuth:
      type: http
      description: "Once authorized, all subsequent requests must include an `Authorization` header\n with the granted `access_token`. See the OAuth2 Authentication path for more information on how to authorize a User.<br><br>\n Example Header: `Authorization: Bearer <access_token>`"
      name: Authorization
      in: header
      bearerFormat: Bearer `<access_token>`
      scheme: bearer
